---
vps:
  hosts:
    wail-portfolio-vps:
      ansible_host: 165.227.128.83
      ansible_user: wail
      ansible_port: 22
      ansible_python_interpreter: /usr/bin/python3

all:
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
